lang/rust: Change cargo flag
unikraft/lib-rust pull request #4
Opened 2023-01-11 11:04 UTC by fabianpatras

Change the cargo flag from `-Z` to `-C` because
the option `symbol-mangling-version` is stable in
`rustc 1.68.0-nightly (388538fc9 2023-01-05)`.

This removes a warning.

Signed-off-by: Fabian Patras <patras.fabi@gmail.com>

2023-01-11 12:10 UTC, mkroening commented on Makefile.uk
> +		-Zbinary_dep_depinfo=y -C symbol-mangling-version=v0 \
Perhaps, we should stay consistent with the formatting:

```suggestion
		-Zbinary_dep_depinfo=y -Csymbol-mangling-version=v0 \
```

2023-01-13 07:39 UTC, razvand requested changes
@fabianpatras, please squash the two commits from this PR.

2023-01-13 09:12 UTC, razvand approved these changes
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-01-13 10:41 UTC, mkroening approved these changes
Looks good to me, but we should pin and enforce the Rust nightly version in the future. 👍

Reviewed-by: Martin Kröning mkroening@posteo.net

2023-12-30 07:19 UTC, merged